# Generated by Django 5.2.1 on 2025-05-19 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Enabled'), (1, 'Suspended'), (2, 'Disabled')], db_index=True, default=0)),
                ('request_to_change', models.CharField(blank=True, choices=[('only_have', 'I only have ...')], default='TUITION_FEE', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('grabbed_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
