# Generated by Django 4.0.3 on 2023-03-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='grabbing_date',
            new_name='grabbed_on',
        ),
    ]
