# Generated by Django 4.0.3 on 2022-05-05 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='grabbing_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='request_to_change',
            field=models.CharField(blank=True, choices=[('only_have', 'I only have ...')], default='TUITION_FEE', max_length=20),
        ),
    ]
