services:
#  db:
#    image: postgres:10-alpine
#    container_name: db
#    environment:
#      - POSTGRES_DB=app
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=supersecretpassword
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

  app:
    container_name: app
    build:
      context: .

    command: sh -c "python manage.py wait_for_db && python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${db_name}
      - DB_USER=${db_user}
      - DB_PASSWORD=${db_pass}
      - DB_HOST=${db_host}
      - DB_PORT=${db_port}

#    depends_on:
#      - db
