# Generated by Django 4.0.3 on 2023-02-26 01:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('selling', models.BigIntegerField(null=True)),
                ('selling_currency', models.CharField(choices=[('CAD', 'CAD'), ('IRT', 'IRT'), ('MYR', 'MYR'), ('NZD', 'NZD'), ('USD', 'USD')], default='CAD', max_length=5)),
                ('buying', models.BigIntegerField(null=True)),
                ('buying_currency', models.CharField(choices=[('CAD', 'CAD'), ('IRT', 'IRT'), ('MYR', 'MYR'), ('NZD', 'NZD'), ('USD', 'USD')], default='IRT', max_length=5)),
                ('purpose', models.CharField(choices=[('GIFT', 'Gift'), ('HELP_MY_FAMILY', 'Help my family'), ('LOAN_REPAYMENT', 'Loan repayment'), ('TRAVELING', 'Traveling'), ('TUITION_FEE', 'Tuition fee')], default='TUITION_FEE', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_seller_deposited', models.BooleanField(default=False)),
                ('is_buyer_deposited', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
