# Generated by Django 5.2.1 on 2025-05-19 03:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('selling_fee', models.DecimalField(decimal_places=3, default=0.005, max_digits=4)),
                ('buying_fee', models.DecimalField(decimal_places=3, default=0.005, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Enabled'), (1, 'Suspended'), (2, 'Disabled')], db_index=True, default=0)),
                ('uuid', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=8, unique=True)),
                ('selling', models.BigIntegerField(null=True)),
                ('selling_currency', models.CharField(choices=[('CAD', 'CAD'), ('IRR', 'IRR'), ('MYR', 'MYR'), ('NZD', 'NZD'), ('USD', 'USD')], default='CAD', max_length=5)),
                ('buying', models.BigIntegerField(null=True)),
                ('buying_currency', models.CharField(choices=[('CAD', 'CAD'), ('IRR', 'IRR'), ('MYR', 'MYR'), ('NZD', 'NZD'), ('USD', 'USD')], default='IRR', max_length=5)),
                ('purpose', models.CharField(choices=[('GIFT', 'Gift'), ('HELP_MY_FAMILY', 'Help my family'), ('LOAN_REPAYMENT', 'Loan repayment'), ('TRAVELING', 'Traveling'), ('TUITION_FEE', 'Tuition fee')], default='TUITION_FEE', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_seller_deposited', models.BooleanField(default=False)),
                ('is_buyer_deposited', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='listings.servicefee')),
            ],
        ),
    ]
