# Generated by Django 4.0.3 on 2022-04-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='listing',
            name='i_have',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='i_want',
            field=models.IntegerField(default=0),
        ),
    ]
