# Generated by Django 4.0.3 on 2022-04-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_price_listing_i_have_listing_i_want'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='i_have',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='i_want',
            field=models.IntegerField(blank=True),
        ),
    ]
