# Generated by Django 4.0.3 on 2022-04-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_is_buyer_deposited_listing_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('STUDENT', 'Freshman'), ('LOAN', 'Sophomore'), ('FAMILY', 'Junior'), ('TRAVEL', 'Senior'), ('INVESTMENT', 'Graduate')], default='STUDENT', max_length=20),
        ),
    ]
