# Generated by Django 4.0.3 on 2022-04-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('GIFT', 'Gift'), ('HELP_MY_FAMILY', 'Help my family'), ('LOAN_REPAYMENT', 'Loan repayment'), ('TRAVELING', 'Traveling'), ('TUITION_FEE', 'Tuition fee')], default='STUDENT', max_length=20),
        ),
    ]
