# Generated by Django 4.0.3 on 2022-04-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_i_have_currency_listing_i_want_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='i_want_currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('IRT', 'IRT'), ('MYR', 'MYR'), ('NZD', 'NZD'), ('USD', 'USD')], default='IRT', max_length=5),
        ),
    ]
