# Generated by Django 4.0.3 on 2022-05-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_i_want_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='i_have',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='i_have_currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='i_want',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='i_want_currency',
        ),
        migrations.AddField(
            model_name='listing',
            name='buying',
            field=models.BigIntegerField(help_text='associated with i_want', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='buying_currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('IRT', 'IRT'), ('MYR', 'MYR'), ('NZD', 'NZD'), ('USD', 'USD')], default='IRT', help_text='associated with i_want_currency', max_length=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='selling',
            field=models.BigIntegerField(help_text='associated with i_have', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='selling_currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('IRT', 'IRT'), ('MYR', 'MYR'), ('NZD', 'NZD'), ('USD', 'USD')], default='CAD', help_text='associated with i_have_currency', max_length=5),
        ),
    ]
