# Generated by Django 4.0.3 on 2022-05-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_listing_i_have_remove_listing_i_have_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buying',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='buying_currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('IRT', 'IRT'), ('MYR', 'MYR'), ('NZD', 'NZD'), ('USD', 'USD')], default='IRT', max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='selling',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='selling_currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('IRT', 'IRT'), ('MYR', 'MYR'), ('NZD', 'NZD'), ('USD', 'USD')], default='CAD', max_length=5),
        ),
    ]
